# Generated by Django 3.0.5 on 2020-06-01 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='short_bio',
            field=models.CharField(max_length=400),
        ),
    ]
